### ISSUE TITLE
Version tag should contain 1 not 0

### ISSUE THREAD

**Issue by matty0ung** [stuartraetaylor/punkapi-export-java#1]
In a lot of places, the XML files contain `<VERSION>0</VERSION>` rather than the `<VERSION>1</VERSION>` that the (infamous) BeerXML standard doc requires.  In some sense, it's not an important field as it's unlikely there will ever be a version other than 1 of BeerXML, but if it's a small fix it would be good to have.

**Comment by stuartraetaylor** [comment]
Hello, thanks for the feedback. I have updated the beerxml exporter to set the version element (#5).
